<template>
    <Head title="E-Challan Pricing" />
    <AdminLayout title="E-Challan Pricing" eyebrow="Service settings">
        <ChallanTabs />
        <section class="mt-5 grid gap-3 sm:grid-cols-3"><Metric label="Dealer searches" :value="stats.total" /><Metric label="Successful" :value="stats.successful" tone="teal" /><Metric label="Revenue" :value="money(stats.revenue)" tone="blue" /></section>
        <section class="mt-5 grid gap-5 xl:grid-cols-[minmax(0,1fr)_360px]"><form class="rounded-lg border border-slate-200 bg-white p-5 shadow-sm" @submit.prevent="submit"><p class="text-xs font-black uppercase tracking-wide text-teal-700">Charge configuration</p><h2 class="mt-2 text-2xl font-black text-slate-950">Set customer and dealer E-Challan prices.</h2><p class="mt-2 text-sm font-semibold leading-7 text-slate-600">Changes apply to future lookups only.</p><div class="mt-6 grid gap-4 sm:grid-cols-2"><Price label="Customer charge" v-model="form.charge" :error="form.errors.charge" /><Price label="Dealer charge" v-model="form.dealer_charge" :error="form.errors.dealer_charge" /></div><button class="mt-6 rounded-lg bg-teal-700 px-5 py-3 text-sm font-black text-white hover:bg-teal-800 disabled:opacity-60" :disabled="form.processing">{{ form.processing?'Saving...':'Save pricing' }}</button></form><aside class="rounded-lg border border-orange-100 bg-orange-50 p-5"><p class="text-xs font-black uppercase tracking-wide text-orange-700">Pricing note</p><h3 class="mt-2 text-xl font-black text-slate-950">Fine values are not platform revenue.</h3><p class="mt-3 text-sm font-semibold leading-7 text-slate-600">Only the lookup charge is collected by the platform. Returned challan amounts belong to enforcement authorities.</p></aside></section>
    </AdminLayout>
</template>
<script setup lang="ts">
import {defineComponent,h} from 'vue'; import {Head,useForm} from '@inertiajs/vue3'; import AdminLayout from '@/Layouts/AdminLayout.vue'; import ChallanTabs from '@/Components/Admin/ChallanTabs.vue';
const props=defineProps<{charges:{customer:number;dealer:number};stats:{total:number;successful:number;revenue:number};actions:{update:string}}>(); const form=useForm({charge:props.charges.customer,dealer_charge:props.charges.dealer}); const submit=()=>form.post(props.actions.update,{preserveScroll:true}); const money=(v:number|string)=>`Rs ${new Intl.NumberFormat('en-IN',{maximumFractionDigits:2}).format(Number(v||0))}`;
const Metric=defineComponent({props:{label:{type:String,required:true},value:{type:[String,Number],required:true},tone:{type:String,default:'slate'}},setup(p){const c:any={slate:'border-slate-200 bg-white',teal:'border-teal-100 bg-teal-50',blue:'border-blue-100 bg-blue-50'};return()=>h('div',{class:['rounded-lg border p-4 shadow-sm',c[p.tone]]},[h('p',{class:'text-2xl font-black text-slate-950'},typeof p.value==='number'?new Intl.NumberFormat('en-IN').format(p.value):p.value),h('p',{class:'mt-1 text-xs font-black uppercase tracking-wide text-slate-500'},p.label)]);}}); const Price=defineComponent({props:{label:{type:String,required:true},modelValue:{type:[String,Number],required:true},error:{type:String,default:''}},emits:['update:modelValue'],setup(p,{emit}){return()=>h('label',[h('span',{class:'mb-2 block text-sm font-black text-slate-700'},p.label),h('div',{class:'relative'},[h('span',{class:'pointer-events-none absolute inset-y-0 left-0 grid w-11 place-items-center font-black text-slate-500'},'Rs'),h('input',{class:'admin-input pl-11',type:'number',min:'0',step:'0.01',required:true,value:p.modelValue,onInput:(e:any)=>emit('update:modelValue',e.target.value)})]),p.error?h('p',{class:'mt-2 text-xs font-bold text-red-600'},p.error):null]);}});
</script>
