<template>
    <Head title="Combined E-Challan Ledger" />
    <AdminLayout title="Combined E-Challan Ledger" eyebrow="Service tracking">
        <ChallanTabs />
        <section class="mt-5 rounded-lg border border-slate-200 bg-white p-5 shadow-sm"><p class="text-xs font-black uppercase tracking-wide text-teal-700">Unified activity</p><h2 class="mt-2 text-3xl font-black text-slate-950">Dealer and customer challan searches in one timeline.</h2><p class="mt-2 max-w-3xl text-sm font-semibold leading-7 text-slate-600">Compare channel volume, lookup outcomes, platform charges and the total fines returned by authorities.</p></section>
        <section class="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><Metric label="Filtered searches" :value="stats.total" /><Metric label="Successful" :value="stats.successful" tone="teal" /><Metric label="Failed" :value="stats.failed" tone="red" /><Metric label="Revenue" :value="money(stats.revenue)" tone="blue" /><Metric label="Fine exposure" :value="money(stats.fine_amount)" tone="orange" /><Metric label="Customer / Dealer" :value="`${money(stats.customer_charge)} / ${money(stats.dealer_charge)}`" /></section>
        <section class="mt-5 rounded-lg border border-slate-200 bg-white p-5 shadow-sm"><form class="grid gap-3 md:grid-cols-2 xl:grid-cols-[1.3fr_190px_190px_auto]" @submit.prevent="filter"><Field label="Vehicle number"><input v-model="form.search" class="admin-input uppercase" type="search" placeholder="BR01AB1234" /></Field><Field label="From"><input v-model="form.from_date" class="admin-input" type="date" /></Field><Field label="To"><input v-model="form.to_date" class="admin-input" type="date" /></Field><div class="flex items-end gap-2 md:col-span-2 xl:col-span-1"><button class="h-12 rounded-lg bg-slate-950 px-5 text-sm font-black text-white hover:bg-teal-700">Filter</button><Link href="/admin/service-tracking/challan-search" class="grid h-12 place-items-center rounded-lg border border-slate-200 px-5 text-sm font-black text-slate-700 hover:bg-slate-50">Clear</Link></div></form></section>
        <section class="mt-5 overflow-hidden rounded-lg border border-slate-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="w-full min-w-[1150px] text-left text-sm"><thead class="bg-slate-50 text-xs font-black uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-3">Channel</th><th class="px-5 py-3">User</th><th class="px-5 py-3">Vehicle</th><th class="px-5 py-3">Challans</th><th class="px-5 py-3">Fine amount</th><th class="px-5 py-3">Outcome</th><th class="px-5 py-3">Charge</th><th class="px-5 py-3">Created</th><th class="px-5 py-3 text-right">Actions</th></tr></thead><tbody class="divide-y divide-slate-100">
            <tr v-for="item in searches.data" :key="`${item.type}-${item.id}`" class="hover:bg-slate-50"><td class="px-5 py-4"><Channel :type="item.type" /></td><td class="px-5 py-4"><p class="font-black text-slate-950">{{ item.user_name }}</p><p class="mt-1 text-xs font-semibold text-slate-500">{{ item.phone || 'Phone unavailable' }}</p></td><td class="px-5 py-4 font-black uppercase text-slate-950">{{ item.vehicle_number }}</td><td class="px-5 py-4 font-black text-slate-950">{{ item.challan_count }}</td><td class="px-5 py-4 font-black text-orange-700">{{ money(item.fine_amount) }}</td><td class="px-5 py-4"><Status :success="item.is_success" /></td><td class="px-5 py-4 font-black text-slate-950">{{ money(item.charge_amount) }}</td><td class="px-5 py-4 font-semibold text-slate-600">{{ item.created_at || 'N/A' }}</td><td class="px-5 py-4"><div class="flex justify-end gap-2"><Link :href="item.show_url" class="rounded-lg bg-slate-950 px-3 py-2 text-xs font-black text-white hover:bg-teal-700">View</Link><a v-if="item.is_success" :href="item.pdf_url" class="rounded-lg border border-slate-200 px-3 py-2 text-xs font-black text-slate-700 hover:bg-slate-50">PDF</a></div></td></tr>
            <tr v-if="!searches.data.length"><td colspan="9" class="px-5 py-14 text-center"><p class="text-lg font-black text-slate-950">No challan activity found</p></td></tr>
        </tbody></table></div><div class="border-t border-slate-100 px-5 py-4"><PaginationLinks :links="searches.links" /></div></section>
    </AdminLayout>
</template>
<script setup lang="ts">
import {defineComponent,h,reactive} from 'vue';import {Head,Link,router} from '@inertiajs/vue3';import AdminLayout from '@/Layouts/AdminLayout.vue';import PaginationLinks from '@/Components/Admin/PaginationLinks.vue';import ChallanTabs from '@/Components/Admin/ChallanTabs.vue';
type Item={id:number;type:'dealer'|'customer';user_name:string;phone?:string|null;vehicle_number:string;challan_count:number;fine_amount:number;is_success:boolean;charge_amount:number;created_at?:string|null;show_url:string;pdf_url:string};const props=defineProps<{searches:{data:Item[];links:Array<{url:string|null;label:string;active:boolean}>};filters:{search:string;from_date:string;to_date:string};stats:{total:number;successful:number;failed:number;revenue:number;fine_amount:number;customer_charge:number;dealer_charge:number}}>();const form=reactive({...props.filters});const money=(v:number|string)=>`Rs ${new Intl.NumberFormat('en-IN',{maximumFractionDigits:2}).format(Number(v||0))}`;const filter=()=>{const p:Record<string,string>={};Object.entries(form).forEach(([k,v])=>{if(v)p[k]=v;});router.get('/admin/service-tracking/challan-search',p,{preserveState:true,preserveScroll:true});};
const Field=defineComponent({props:{label:{type:String,required:true}},setup(p,{slots}){return()=>h('label',[h('span',{class:'mb-2 block text-sm font-black text-slate-700'},p.label),slots.default?.()]);}});const Metric=defineComponent({props:{label:{type:String,required:true},value:{type:[String,Number],required:true},tone:{type:String,default:'slate'}},setup(p){const c:any={slate:'border-slate-200 bg-white',teal:'border-teal-100 bg-teal-50',red:'border-red-100 bg-red-50',blue:'border-blue-100 bg-blue-50',orange:'border-orange-100 bg-orange-50'};return()=>h('div',{class:['rounded-lg border p-4 shadow-sm',c[p.tone]]},[h('p',{class:'text-xl font-black text-slate-950'},typeof p.value==='number'?new Intl.NumberFormat('en-IN').format(p.value):p.value),h('p',{class:'mt-1 text-xs font-black uppercase tracking-wide text-slate-500'},p.label)]);}});const Status=defineComponent({props:{success:{type:Boolean,required:true}},setup(p){return()=>h('span',{class:['inline-flex rounded-md px-2.5 py-1 text-xs font-black',p.success?'bg-teal-50 text-teal-700 ring-1 ring-teal-100':'bg-red-50 text-red-700 ring-1 ring-red-100']},p.success?'Successful':'Failed');}});const Channel=defineComponent({props:{type:{type:String,required:true}},setup(p){return()=>h('span',{class:['inline-flex rounded-md px-2.5 py-1 text-xs font-black',p.type==='dealer'?'bg-blue-50 text-blue-700 ring-1 ring-blue-100':'bg-orange-50 text-orange-700 ring-1 ring-orange-100']},p.type==='dealer'?'Dealer':'Customer');}});
</script>
