<template>
    <Head :title="`${page.provider} Service ${search.vehicle_number}`" />
    <AdminLayout :title="page.title" eyebrow="Service operations">
        <ServiceHistoryTabs />
        <section class="mt-5 rounded-lg border border-slate-200 bg-white p-5 shadow-sm"><div class="flex flex-col gap-5 lg:flex-row lg:items-start lg:justify-between"><div><Link :href="search.actions.back" class="inline-flex rounded-lg border border-slate-200 px-4 py-2.5 text-sm font-semibold text-slate-700 hover:bg-slate-50">Back to searches</Link><p class="mt-5 text-xs font-semibold uppercase tracking-wide text-teal-700">{{ page.provider }} workshop timeline</p><h2 class="mt-2 text-3xl font-semibold uppercase text-slate-950">{{ search.vehicle_number }}</h2><p class="mt-2 text-sm font-semibold text-slate-600">{{ search.subject_name }}<span v-if="search.subject_phone"> / {{ search.subject_phone }}</span></p></div><div class="flex flex-wrap items-center gap-2"><Status :success="search.is_success" /><a v-if="search.is_success" :href="search.actions.pdf" class="rounded-lg bg-slate-950 px-4 py-3 text-sm font-semibold text-white hover:bg-teal-700">Download PDF</a></div></div></section>
        <section class="mt-5 grid gap-3 sm:grid-cols-3"><Tile label="Services found" :value="`${search.service_count} records`" /><Tile :label="page.channel === 'dealer' ? 'Amount charged' : 'Amount paid'" :value="money(search.amount)" tone="teal" /><Tile label="Search date" :value="search.created_at || 'N/A'" tone="orange" /></section>
        <section v-if="search.error_message" class="mt-5 rounded-lg border border-red-100 bg-red-50 px-5 py-4 text-sm font-bold text-red-700">{{ search.error_message }}</section>
        <section class="mt-5 overflow-hidden rounded-lg border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-100 px-5 py-4"><p class="text-xs font-semibold uppercase tracking-wide text-teal-700">Workshop records</p><h3 class="mt-1 text-xl font-semibold text-slate-950">{{ search.records.length }} service visits</h3></div><div v-if="search.records.length" class="overflow-x-auto"><table class="w-full min-w-[1320px] text-left text-sm"><thead class="bg-slate-50 text-xs font-semibold uppercase tracking-wide text-slate-500"><tr><th class="px-4 py-3">Date</th><th class="px-4 py-3">Category / Work</th><th class="px-4 py-3">Workshop</th><th class="px-4 py-3">Job Card / RO</th><th class="px-4 py-3">Bill / Assistant</th><th class="px-4 py-3">Parts</th><th class="px-4 py-3">Labour</th><th class="px-4 py-3">Total</th><th class="px-4 py-3">Mileage</th><th class="px-4 py-3">Status</th></tr></thead><tbody class="divide-y divide-slate-100"><tr v-for="(record,index) in search.records" :key="index"><td class="px-4 py-4 font-semibold text-slate-950">{{ record.date || 'N/A' }}</td><td class="px-4 py-4"><p class="font-bold text-slate-700">{{ record.category || 'N/A' }}</p><p class="mt-1 text-xs font-semibold text-slate-500">{{ record.work_type || '' }}</p></td><td class="px-4 py-4"><p class="font-semibold text-slate-950">{{ record.dealer_name || 'N/A' }}</p><p class="mt-1 max-w-[220px] text-xs font-semibold text-slate-500">{{ record.location || '' }}</p></td><td class="px-4 py-4 font-semibold text-slate-600">{{ record.job_card || 'N/A' }} / {{ record.ro_no || 'N/A' }}</td><td class="px-4 py-4"><p class="font-semibold text-slate-600">{{ record.bill_no || 'N/A' }}</p><p class="mt-1 text-xs font-semibold text-slate-500">{{ record.bill_date || record.assistant || '' }}</p></td><td class="px-4 py-4 font-semibold text-slate-950">{{ money(record.part_amount || 0) }}</td><td class="px-4 py-4 font-semibold text-slate-950">{{ money(record.labour_amount || 0) }}</td><td class="px-4 py-4 font-semibold text-teal-700">{{ money(record.total_amount || 0) }}</td><td class="px-4 py-4 font-semibold text-slate-600">{{ record.mileage || 'N/A' }}</td><td class="px-4 py-4 font-semibold text-slate-600">{{ record.status || 'N/A' }}</td></tr></tbody></table></div><div v-else class="px-5 py-14 text-center"><p class="text-lg font-semibold text-slate-950">No workshop records available</p><p class="mt-2 text-sm font-semibold text-slate-500">The search summary remains available above.</p></div></section>
    </AdminLayout>
</template>
<script setup lang="ts">
import {defineComponent,h} from 'vue';import {Head,Link} from '@inertiajs/vue3';import AdminLayout from '@/Layouts/AdminLayout.vue';import ServiceHistoryTabs from '@/Components/Admin/ServiceHistoryTabs.vue';
type Row={date?:string|null;category?:string|null;work_type?:string|null;dealer_name?:string|null;location?:string|null;job_card?:string|null;ro_no?:string|null;bill_no?:string|null;bill_date?:string|null;assistant?:string|null;part_amount?:number;labour_amount?:number;total_amount?:number;mileage?:string|number|null;status?:string|null};type Search={vehicle_number:string;service_count:number;amount:number;is_success:boolean;error_message?:string|null;created_at?:string|null;subject_name:string;subject_phone?:string|null;records:Row[];actions:{back:string;pdf:string}};defineProps<{page:{title:string;provider:string;channel:'dealer'|'customer'};search:Search}>();const money=(v:number|string)=>`Rs ${new Intl.NumberFormat('en-IN',{maximumFractionDigits:2}).format(Number(v||0))}`;
const Status=defineComponent({props:{success:{type:Boolean,required:true}},setup(p){return()=>h('span',{class:['inline-flex rounded-md px-3 py-2 text-xs font-semibold',p.success?'bg-teal-50 text-teal-700 ring-1 ring-teal-100':'bg-red-50 text-red-700 ring-1 ring-red-100']},p.success?'Successful lookup':'Failed lookup');}});const Tile=defineComponent({props:{label:{type:String,required:true},value:{type:String,required:true},tone:{type:String,default:'slate'}},setup(p){const c:any={slate:'border-slate-200 bg-white',teal:'border-teal-100 bg-teal-50',orange:'border-orange-100 bg-orange-50'};return()=>h('div',{class:['rounded-lg border p-4 shadow-sm',c[p.tone]]},[h('p',{class:'text-xs font-semibold uppercase tracking-wide text-slate-500'},p.label),h('p',{class:'mt-2 text-lg font-semibold text-slate-950'},p.value)]);}});
</script>
